// Builds THIRD_PARTY_LICENSES.md: every open-source package that ships inside
// Headroom (Rust crates via cargo-about, plus the production npm packages),
// with its license text. Run: `node scripts/credits.mjs` (needs cargo-about:
// `cargo install --locked cargo-about --features cli`).
import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;

// --- npm: walk the production dependency tree ---
const tree = JSON.parse(execFileSync("npm", ["ls", "--omit=dev", "--all", "--json"], { cwd: root, encoding: "utf8" }));
const pkgs = new Map();
(function walk(deps = {}) {
  for (const [name, info] of Object.entries(deps)) {
    if (!pkgs.has(name)) pkgs.set(name, info.version);
    walk(info.dependencies);
  }
})(tree.dependencies);

function licenseText(dir) {
  const file = readdirSync(dir).find((f) => /^(licen[cs]e|copying)(\.|$)/i.test(f));
  return file ? readFileSync(join(dir, file), "utf8").trim() : null;
}

const npmSections = [...pkgs.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, version]) => {
    const dir = join(root, "node_modules", name);
    const meta = existsSync(join(dir, "package.json")) ? JSON.parse(readFileSync(join(dir, "package.json"), "utf8")) : {};
    const text = existsSync(dir) ? licenseText(dir) : null;
    return `### ${name} ${version} (${meta.license ?? "see repository"})\n\n` + (text ? "```\n" + text + "\n```\n" : "_No license file in the package; license per package.json._\n");
  });

// --- Rust: cargo-about renders crates grouped by license ---
const rust = execFileSync("cargo", ["about", "generate", "about.hbs"], { cwd: join(root, "src-tauri"), encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });

const out = `# Third-party licenses

Headroom is MIT-licensed (see LICENSE). It ships with the open-source packages below; their licenses ask us to reproduce these notices. Thank you to everyone who built them.

_Generated by \`scripts/credits.mjs\`. Do not edit by hand._

## JavaScript packages (${pkgs.size})

${npmSections.join("\n")}
## Rust crates

${rust.trim()}
`;
writeFileSync(join(root, "THIRD_PARTY_LICENSES.md"), out);
console.log(`THIRD_PARTY_LICENSES.md: ${pkgs.size} npm packages + Rust crates, ${Math.round(out.length / 1024)} KB`);
